


GET http://localhost:4004/odata/v4/asset/Asset

###
POST http://localhost:4004/odata/v4/asset/Asset(ID=1001,IsActiveEntity=true)/assign
Content-Type: application/json

{
  "employeeID": 101
}

###
POST http://localhost:4004/odata/v4/asset/Asset(ID=1001,IsActiveEntity=true)/unassign
